export const CREATE_BUS_REQUEST = "CREATE_BUS_REQUEST";
export const CREATE_BUS_SUCCESS = "CREATE_BUS_SUCCESS";
export const CREATE_BUS_FAILURE = "CREATE_BUS_FAILURE";
export const CREATE_BUS_RESET = "CREATE_BUS_RESET";

export const FETCH_BUSES_REQUEST = "FETCH_BUSES_REQUEST";
export const FETCH_BUSES_SUCCESS = "FETCH_BUSES_SUCCESS";
export const FETCH_BUSES_FAILURE = "FETCH_BUSES_FAILURE";
export const FETCH_BUSES_RESET = "FETCH_BUSES_RESET";

export const EDIT_BUS_REQUEST = "EDIT_BUS_REQUEST";
export const EDIT_BUS_SUCCESS = "EDIT_BUS_SUCCESS";
export const EDIT_BUS_FAILURE = "EDIT_BUS_FAILURE";
export const EDIT_BUS_RESET = "EDIT_BUS_RESET";

export const FETCH_SINGLE_BUS_REQUEST = "FETCH_SINGLE_BUS_REQUEST";
export const FETCH_SINGLE_BUS_SUCCESS = "FETCH_SINGLE_BUS_SUCCESS";
export const FETCH_SINGLE_BUS_FAILURE = "FETCH_SINGLE_BUS_FAILURE";
export const FETCH_SINGLE_BUS_RESET = "FETCH_SINGLE_BUS_RESET";

export const DELETE_BUS_REQUEST = "DELETE_BUS_REQUEST";
export const DELETE_BUS_SUCCESS = "DELETE_BUS_SUCCESS";
export const DELETE_BUS_FAILURE = "DELETE_BUS_FAILURE";
export const DELETE_BUS_RESET = "DELETE_BUS_RESET";

export const SEARCH_BUS_REQUEST  = "SEARCH_BUS_REQUEST";
export const SEARCH_BUS_SUCCESS = "SEARCH_BUS_SUCCESS";
export const SEARCH_BUS_FAILURE = "SEARCH_BUS_FAILURE";
export const SEARCH_BUS_RESET = "SEARCH_BUS_RESET";


export const DELETE_BUS_UPDATE_LIST = "DELETE_BUS_UPDATE_LIST"