export const UPLOAD_BUS_REQUEST = "UPLOAD_BUS_REQUEST";
export const UPLOAD_BUS_SUCCESS = "UPLOAD_BUS_SUCCESS";
export const UPLOAD_BUS_FAILURE = "UPLOAD_BUS_FAILURE";
export const UPLOAD_BUS_RESET = "UPLOAD_BUS_RESET";

export const FETCH_BUSES_REQUEST = "FETCH_BUSES_REQUEST";
export const FETCH_BUSES_SUCCESS = "FETCH_BUSES_SUCCESS";
export const FETCH_BUSES_FAILURE = "FETCH_BUSES_FAILURE";
export const FETCH_BUSES_RESET = "FETCH_BUSES_RESET";

export const CREATE_BUS_REQUEST = "CREATE_BUS_REQUEST";
export const CREATE_BUS_SUCCESS = "CREATE_BUS_SUCCESS";
export const CREATE_BUS_FAILURE = "CREATE_BUS_FAILURE";
export const CREATE_BUS_RESET = "CREATE_BUS_RESET";


export const UPDATE_BUS_REQUEST = "UPDATE_BUS_REQUEST";
export const UPDATE_BUS_SUCCESS = "UPDATE_BUS_SUCCESS";
export const UPDATE_BUS_FAILURE = "UPDATE_BUS_FAILURE";
export const UPDATE_BUS_RESET = "UPDATE_BUS_RESET"


export const DELETE_BUS_SUCCESS = "DELETE_BUS_SUCCESS";
export const DELETE_BUS_FAILURE = "DELETE_BUS_FAILURE";
export const DELETE_BUS_RESET = "DELETE_BUS_RESET"
