export const FETCH_BUS_STATS_REQUEST = "FETCH_BUS_STATS_REQUEST";
export const FETCH_BUS_STATS_SUCCESS = "FETCH_BUS_STATS_SUCCESS";
export const FETCH_BUS_STATS_FAILURE = "FETCH_BUS_STATS_FAILURE";
export const FETCH_BUS_STATS_RESET = "FETCH_BUS_STATS_RESET";


export const CREATE_BUS_STAT_REQUEST = "CREATE_BUS_STAT_REQUEST"
export const CREATE_BUS_STAT_SUCCESS = "CREATE_BUS_STAT_SUCCESS"
export const CREATE_BUS_STAT_FAILURE = "CREATE_BUS_STAT_FAILURE"
export const CREATE_BUS_STAT_RESET = "CREATE_BUS_STAT_RESET"