export const FETCH_BUS_STATS_REQUEST = "FETCH_BUS_STATS_REQUEST";
export const FETCH_BUS_STATS_SUCCESS = "FETCH_BUS_STATS_SUCCESS";
export const FETCH_BUS_STATS_FAILURE = "FETCH_BUS_STATS_FAILURE";
export const FETCH_BUS_STATS_RESET = "FETCH_BUS_STATS_RESET";

export const CREATE_BUS_STAT_REQUEST = "CREATE_BUS_STAT_REQUEST";
export const CREATE_BUS_STAT_SUCCESS = "CREATE_BUS_STAT_SUCCESS";
export const CREATE_BUS_STAT_FAILURE = "CREATE_BUS_STAT_FAILURE";
export const CREATE_BUS_STAT_RESET = "CREATE_BUS_STAT_RESET";

export const UPLOAD_BUS_STAT_REQUEST = "UPLOAD_BUS_STAT_REQUEST";
export const UPLOAD_BUS_STAT_SUCCESS = "UPLOAD_BUS_STAT_SUCCESS";
export const UPLOAD_BUS_STAT_FAILURE = "UPLOAD_BUS_STAT_FAILURE";
export const UPLOAD_BUS_STAT_PROGRESS = "UPLOAD_BUS_STAT_PROGRESS";
export const UPLOAD_BUS_STAT_RESET = "UPLOAD_BUS_STAT_RESET";

export const FETCH_SINGLE_BUS_STAT_REQUEST = "FETCH_SINGLE_BUS_STAT_REQUEST";
export const FETCH_SINGLE_BUS_STAT_SUCCESS = "FETCH_SINGLE_BUS_STAT_SUCCESS";
export const FETCH_SINGLE_BUS_STAT_FAILURE = "FETCH_SINGLE_BUS_STAT_FAILURE";
export const FETCH_SINGLE_BUS_STAT_RESET = "FETCH_SINGLE_BUS_STAT_RESET";

export const EDIT_BUS_STAT_REQUEST = "EDIT_BUS_STAT_REQUEST";
export const EDIT_BUS_STAT_SUCCESS = "EDIT_BUS_STAT_SUCCESS";
export const EDIT_BUS_STAT_FAILURE = "EDIT_BUS_STAT_FAILURE";
export const EDIT_BUS_STAT_RESET = "EDIT_BUS_STAT_RESET";

export const DELETE_BUS_STAT_REQUEST = "DELETE_BUS_STAT_REQUEST";
export const DELETE_BUS_STAT_SUCCESS = "DELETE_BUS_STAT_SUCCESS";
export const DELETE_BUS_STAT_FAILURE = "DELETE_BUS_STAT_FAILURE";
export const DELETE_BUS_STAT_RESET = "DELETE_BUS_STAT_RESET";

export const DELETE_BUS_STAT_UPDATE_LIST = "DELETE_BUS_STAT_UPDATE_LIST";
