export const GENERATE_SCHEDULE_REQUEST = "GENERATE_SCHEDULE_REQUEST"
export const GENERATE_SCHEDULE_SUCCESS = "GENERATE_SCHEDULE_SUCCESS"
export const GENERATE_SCHEDULE_FAILURE = "GENERATE_SCHEDULE_FAILURE"
export const GENERATE_SCHEDULE_RESET = "GENERATE_SCHEDULE_RESET"


export const GET_SCHEDULE_REQUEST = "GET_SCHEDULE_REQUEST"
export const GET_SCHEDULE_SUCCESS = "GET_SCHEDULE_SUCCESS"
export const GET_SCHEDULE_FAILURE = "GET_SCHEDULE_FAILURE"
export const GET_SCHEDULE_RESET  = "GET_SCHEDULE_RESET"