export const GENERATE_SCHEDULE_REQUEST = "GENERATE_SCHEDULE_REQUEST";
export const GENERATE_SCHEDULE_SUCCESS = "GENERATE_SCHEDULE_SUCCESS";
export const GENERATE_SCHEDULE_FAILURE = "GENERATE_SCHEDULE_FAILURE";
export const GENERATE_SCHEDULE_RESET = "GENERATE_SCHEDULE_RESET";

export const GET_SCHEDULE_REQUEST = "GET_SCHEDULE_REQUEST";
export const GET_SCHEDULE_SUCCESS = "GET_SCHEDULE_SUCCESS";
export const GET_SCHEDULE_FAILURE = "GET_SCHEDULE_FAILURE";
export const GET_SCHEDULE_RESET = "GET_SCHEDULE_RESET";

export const CREATE_SCHEDULE_REQUEST = "CREATE_SCHEDULE_REQUEST";
export const CREATE_SCHEDULE_SUCCESS = "CREATE_SCHEDULE_SUCCESS";
export const CREATE_SCHEDULE_FAILURE = "CREATE_SCHEDULE_FAILURE";
export const CREATE_SCHEDULE_RESET = "CREATE_SCHEDULE_RESET";

export const DELETE_SCHEDULE_REQUEST = "DELETE_SCHEDULE_REQUEST";
export const DELETE_SCHEDULE_SUCCESS = "DELETE_SCHEDULE_SUCCESS";
export const DELETE_SCHEDULE_FAILURE = "DELETE_SCHEDULE_FAILURE";
export const DELETE_SCHEDULE_RESET = "DELETE_SCHEDULE_RESET";

export const FETCH_SINGLE_SCHEDULE_REQUEST = "FETCH_SINGLE_SCHEDULE_REQUEST";
export const FETCH_SINGLE_SCHEDULE_SUCCESS = "FETCH_SINGLE_SCHEDULE_SUCCESS";
export const FETCH_SINGLE_SCHEDULE_FAILURE = "FETCH_SINGLE_SCHEDULE_FAILURE";
export const FETCH_SINGLE_SCHEDULE_RESET = "FETCH_SINGLE_SCHEDULE_RESET";

export const UPDATE_SCHEDULE_REQUEST = "UPDATE_SCHEDULE_REQUEST";
export const UPDATE_SCHEDULE_SUCCESS = "UPDATE_SCHEDULE_SUCCESS";
export const UPDATE_SCHEDULE_FAILURE = "UPDATE_SCHEDULE_FAILURE";
export const UPDATE_SCHEDULE_RESET = "UPDATE_SCHEDULE_RESET";

export const DELETE_BULK_SCHEDULE_REQUEST = "DELETE_BULK_SCHEDULE_REQUEST";
export const DELETE_BULK_SCHEDULE_SUCCESS = "DELETE_BULK_SCHEDULE_SUCCESS";
export const DELETE_BULK_SCHEDULE_FAILURE = "DELETE_BULK_SCHEDULE_FAILURE";
export const DELETE_BULK_SCHEDULE_RESET = "DELETE_BULK_SCHEDULE_RESET";
