export const CREATE_DRIVER_REQUEST = "CREATE_DRIVER_REQUEST";
export const CREATE_DRIVER_SUCCESS = "CREATE_DRIVER_SUCCESS";
export const CREATE_DRIVER_FAILURE = "CREATE_DRIVER_FAILURE";
export const CREATE_DRIVER_RESET = "CREATE_DRIVER_RESET";

export const FETCH_DRIVERS_REQUEST = "FETCH_DRIVERS_REQUEST";
export const FETCH_DRIVERS_SUCCESS = "FETCH_DRIVERS_SUCCESS";
export const FETCH_DRIVERS_FAILURE = "FETCH_DRIVERS_FAILURE";
export const FETCH_DRIVERS_RESET = "FETCH_DRIVERS_RESET";

export const EDIT_DRIVER_REQUEST = "EDIT_DRIVER_REQUEST";
export const EDIT_DRIVER_SUCCESS = "EDIT_DRIVER_SUCCESS";
export const EDIT_DRIVER_FAILURE = "EDIT_DRIVER_FAILURE";
export const EDIT_DRIVER_RESET = "EDIT_DRIVER_RESET";

export const FETCH_SINGLE_DRIVER_REQUEST = "FETCH_SINGLE_DRIVER_REQUEST";
export const FETCH_SINGLE_DRIVER_SUCCESS = "FETCH_SINGLE_DRIVER_SUCCESS";
export const FETCH_SINGLE_DRIVER_FAILURE = "FETCH_SINGLE_DRIVER_FAILURE";
export const FETCH_SINGLE_DRIVER_RESET = "FETCH_SINGLE_DRIVER_RESET";

export const DELETE_DRIVER_REQUEST = "DELETE_DRIVER_REQUEST";
export const DELETE_DRIVER_SUCCESS = "DELETE_DRIVER_SUCCESS";
export const DELETE_DRIVER_FAILURE = "DELETE_DRIVER_FAILURE";
export const DELETE_DRIVER_RESET = "DELETE_DRIVER_RESET";
