export const CREATE_DRIVER_REQUEST = "CREATE_DRIVER_REQUEST"
export const CREATE_DRIVER_SUCCESS = "CREATE_DRIVER_SUCCESS"
export const CREATE_DRIVER_FAILURE = "CREATE_DRIVER_FAILURE"

export const RESET_DRIVER = "RESET_DRIVER";