export const FETCH_STOPS_REQUEST = "FETCH_STOPS_REQUEST"
export const FETCH_STOPS_SUCCESS = "FETCH_STOPS_SUCCESS"
export const FETCH_STOPS_FAILURE = "FETCH_STOPS_FAILURE"
export const FETCH_STOPS_RESET = "FETCH_STOPS_RESET"