export const CREATE_ROUTE_REQUEST = "CREATE_ROUTE_REQUEST";
export const CREATE_ROUTE_SUCCESS = "CREATE_ROUTE_SUCCESS";
export const CREATE_ROUTE_FAILURE = "CREATE_ROUTE_FAILURE";
export const CREATE_ROUTE_RESET = "CREATE_ROUTE_RESET";

export const FETCH_ROUTES_REQUEST = "FETCH_ROUTES_REQUEST";
export const FETCH_ROUTES_SUCCESS = "FETCH_ROUTES_SUCCESS";
export const FETCH_ROUTES_FAILURE = "FETCH_ROUTES_FAILURE";
export const FETCH_ROUTES_RESET = "FETCH_ROUTES_RESET";

export const EDIT_ROUTE_REQUEST = "EDIT_ROUTE_REQUEST";
export const EDIT_ROUTE_SUCCESS = "EDIT_ROUTE_SUCCESS";
export const EDIT_ROUTE_FAILURE = "EDIT_ROUTE_FAILURE";
export const EDIT_ROUTE_RESET = "EDIT_ROUTE_RESET";

export const FETCH_SINGLE_ROUTE_REQUEST = "FETCH_SINGLE_ROUTE_REQUEST";
export const FETCH_SINGLE_ROUTE_SUCCESS = "FETCH_SINGLE_ROUTE_SUCCESS";
export const FETCH_SINGLE_ROUTE_FAILURE = "FETCH_SINGLE_ROUTE_FAILURE";
export const FETCH_SINGLE_ROUTE_RESET = "FETCH_SINGLE_ROUTE_RESET";

export const DELETE_ROUTE_REQUEST = "DELETE_ROUTE_REQUEST";
export const DELETE_ROUTE_SUCCESS = "DELETE_ROUTE_SUCCESS";
export const DELETE_ROUTE_FAILURE = "DELETE_ROUTE_FAILURE";
export const DELETE_ROUTE_RESET = "DELETE_ROUTE_RESET";

export const SEARCH_ROUTE_REQUEST  = "SEARCH_ROUTE_REQUEST";
export const SEARCH_ROUTE_SUCCESS = "SEARCH_ROUTE_SUCCESS";
export const SEARCH_ROUTE_FAILURE = "SEARCH_ROUTE_FAILURE";
export const SEARCH_ROUTE_RESET = "SEARCH_ROUTE_RESET";


export const DELETE_ROUTE_UPDATE_LIST = "DELETE_ROUTE_UPDATE_LIST"