export const CREATE_TICKETER_REQUEST = "CREATE_TICKETER_REQUEST";
export const CREATE_TICKETER_SUCCESS = "CREATE_TICKETER_SUCCESS";
export const CREATE_TICKETER_FAILURE = "CREATE_TICKETER_FAILURE";
export const CREATE_TICKETER_RESET = "CREATE_TICKETER_RESET";

export const FETCH_TICKETERS_REQUEST = "FETCH_TICKETERS_REQUEST";
export const FETCH_TICKETERS_SUCCESS = "FETCH_TICKETERS_SUCCESS";
export const FETCH_TICKETERS_FAILURE = "FETCH_TICKETERS_FAILURE";
export const FETCH_TICKETERS_RESET = "FETCH_TICKETERS_RESET";

export const EDIT_TICKETER_REQUEST = "EDIT_TICKETER_REQUEST";
export const EDIT_TICKETER_SUCCESS = "EDIT_TICKETER_SUCCESS";
export const EDIT_TICKETER_FAILURE = "EDIT_TICKETER_FAILURE";
export const EDIT_TICKETER_RESET = "EDIT_TICKETER_RESET";

export const FETCH_SINGLE_TICKETER_REQUEST = "FETCH_SINGLE_TICKETER_REQUEST";
export const FETCH_SINGLE_TICKETER_SUCCESS = "FETCH_SINGLE_TICKETER_SUCCESS";
export const FETCH_SINGLE_TICKETER_FAILURE = "FETCH_SINGLE_TICKETER_FAILURE";
export const FETCH_SINGLE_TICKETER_RESET = "FETCH_SINGLE_TICKETER_RESET";

export const DELETE_TICKETER_REQUEST = "DELETE_TICKETER_REQUEST";
export const DELETE_TICKETER_SUCCESS = "DELETE_TICKETER_SUCCESS";
export const DELETE_TICKETER_FAILURE = "DELETE_TICKETER_FAILURE";
export const DELETE_TICKETER_RESET = "DELETE_TICKETER_RESET";

export const DELETE_TICKETER_UPDATE_LIST = "DELETE_TICKETER_UPDATE_LIST";