export const CHANGE_EMAIL_REQUEST = "CHANGE_EMAIL_REQUEST";
export const CHANGE_EMAIL_SUCCESS = "CHANGE_EMAIL_SUCCESS";
export const CHANGE_EMAIL_FAILURE = "CHANGE_EMAIL_FAILURE";
export const CHANGE_EMAIL_RESET = "CHANGE_EMAIL_RESET";

export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";
export const CHANGE_PASSWORD_RESET = "CHANGE_PASSWORD_RESET";

export const CHANGE_PHONE_NUMBER_REQUEST = "CHANGE_PHONE_NUMBER_REQUEST";
export const CHANGE_PHONE_NUMBER_SUCCESS = "CHANGE_PHONE_NUMBER_SUCCESS";
export const CHANGE_PHONE_NUMBER_FAILURE = "CHANGE_PHONE_NUMBER_FAILURE";
export const CHANGE_PHONE_NUMBER_RESET = "CHANGE_PHONE_NUMBER_RESET";


export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST"
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS"
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE"
export const FETCH_USER_RESET = "FETCH_USER_RESET"


export const ADMIN_CHANGE_OTHER_PASSWORD_REQUEST = "ADMIN_CHANGE_OTHER_PASSWORD_REQUEST"
export const ADMIN_CHANGE_OTHER_PASSWORD_SUCCESS = "ADMIN_CHANGE_OTHER_PASSWORD_SUCCESS"
export const ADMIN_CHANGE_OTHER_PASSWORD_FAILURE = "ADMIN_CHANGE_OTHER_PASSWORD_FAILURE"
export const ADMIN_CHANGE_OTHER_PASSWORD_RESET = "ADMIN_CHANGE_OTHER_PASSWORD_RESET"