export const CREATE_TIMEFRAME_REQUEST = "CREATE_TIMEFRAME_REQUEST";
export const CREATE_TIMEFRAME_SUCCESS = "CREATE_TIMEFRAME_SUCCESS";
export const CREATE_TIMEFRAME_FAILURE = "CREATE_TIMEFRAME_FAILURE";
export const CREATE_TIMEFRAME_RESET = "CREATE_TIMEFRAME_RESET";

export const FETCH_TIMEFRAMES_REQUEST = "FETCH_TIMEFRAMES_REQUEST";
export const FETCH_TIMEFRAMES_SUCCESS = "FETCH_TIMEFRAMES_SUCCESS";
export const FETCH_TIMEFRAMES_FAILURE = "FETCH_TIMEFRAMES_FAILURE";
export const FETCH_TIMEFRAMES_RESET = "FETCH_TIMEFRAMES_RESET";

export const FETCH_SINGLE_TIMEFRAME_REQUEST = "FETCH_SINGLE_TIMEFRAME_REQUEST";
export const FETCH_SINGLE_TIMEFRAME_SUCCESS = "FETCH_SINGLE_TIMEFRAME_SUCCESS";
export const FETCH_SINGLE_TIMEFRAME_FAILURE = "FETCH_SINGLE_TIMEFRAME_FAILURE";
export const FETCH_SINGLE_TIMEFRAME_RESET = "FETCH_SINGLE_TIMEFRAME_RESET"

export const EDIT_TIMEFRAME_REQUEST = "EDIT_TIMEFRAME_REQUEST";
export const EDIT_TIMEFRAME_SUCCESS = "EDIT_TIMEFRAME_SUCCESS";
export const EDIT_TIMEFRAME_FAILURE = "EDIT_TIMEFRAME_FAILURE";
export const EDIT_TIMEFRAME_RESET = "EDIT_TIMEFRAME_RESET";

export const DELETE_TIMEFRAME_REQUEST = "DELETE_TIMEFRAME_REQUEST";
export const DELETE_TIMEFRAME_SUCCESS = "DELETE_TIMEFRAME_SUCCESS";
export const DELETE_TIMEFRAME_FAILURE = "DELETE_TIMEFRAME_FAILURE";
export const DELETE_TIMEFRAME_RESET = "DELETE_TIMEFRAME_RESET";

export const DELETE_TIMEFRAME_UPDATE_LIST = "DELETE_TIMEFRAME_UPADATE_LIST";
export const CREATE_TIMEFRAME_UPDATE_LIST = "CREATE_TIMEFRAME_UPDATE_LIST";
export const EDIT_TIMEFRAME_UPDATE_LIST = "EDIT_TIMEFRAME_UPDATE_LIST";
