export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"
export const LOGIN_RESET = "LOGIN_RESET"

export const CHANGE_EMAIL = "CHANGE_EMAIL";
export const CHANGE_PHONE_NUMBER = "CHANGE_PHONE_NUMBER"